name = "StealthRedirect Hook"
uid = "0df2a276-cc95-40e1-9ba4-f26aa66f0e4f"
version = 1.1
copyright = ""
description = "redirect missiles on stealth unit"
author = "loudpatches"
--icon = "/mods/BrewLAN_Gameplay/WaterGuard/mod_icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
before = {  }
after = {  }
